
services:
  caddy:
    image: caddy:latest
    container_name: caddy
    networks:
      - proxy
    ports:
      - 80:80     #http
      - 443:443   #https
    volumes:
      - caddy_data:/data    #Persistent storage for certificates
      - caddy_config:/config    #For internal Caddy settings
      - /home/shravankale/services/caddy/certs/caddy-root.crt:/data/certs/caddy-root.crt
      - /home/shravankale/services/caddy/Caddyfile:/etc/caddy/Caddyfile:ro #Bind the local Caddyfile to the container
      - /home/shravankale/services/caddy/site:/srv # Future: For static content check docs 
      #Backup data using binding a dir 
      #- - /path/to/caddy_data_on_host:/data
    restart: unless-stopped
volumes:
  caddy_data:
  caddy_config:
networks:
  proxy:
    external: true