services:
  caddy:
    image: caddy:latest
    container_name: caddy
    networks:
      - proxy
    ports:
      - 80:80     # http
      - 443:443   # https
    volumes:
      - caddy_data:/data    # Persistent storage for certificates
      - caddy_config:/config    # For internal Caddy settings
      - ${HOME}/services/caddy/Caddyfile:/etc/caddy/Caddyfile:ro # Bind the local Caddyfile to the container
      - ${HOME}/services/caddy/site:/srv # Future: For static content check docs 
    restart: unless-stopped
volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true
networks:
  proxy:
    external: true
