#Found DashboardL - http://192.168.1.3:8080/dashboard#/
services:
  traefik:
    image: traefik:latest
    container_name: traefik   
    ports:
      - "80:80" #Remove this later? For no http, or build http redirect to https
      - "443:443"
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$HOME/services/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "$HOME/services/traefik/certs:/opt/traefik/certs:ro"
      - "$HOME/services/traefik/config:/opt/traefik/config:ro"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.srv`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
networks:
  proxy:
    external: true