entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  dns-tcp:
    address: ":53/tcp"
  dns-udp:
    address: ":53/udp"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "/opt/traefik/config/tls.yml"
    watch: true

api:
  dashboard: true
  insecure: false