version: "3.9"

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    init: true
    restart: always
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      # HTTPS Router for NextCloud
      - "traefik.http.routers.nextcloud.rule=Host(`ncloud.srv`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"
      # HTTP Router for Redirect
      - "traefik.http.routers.nextcloud-http.rule=Host(`ncloud.srv`)"
      - "traefik.http.routers.nextcloud-http.entrypoints=web"
      - "traefik.http.routers.nextcloud-http.middlewares=https-redirect"
      # HTTPS Redirect Middleware
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      # NextCloud Service
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      # Secure Headers Middleware
      - "traefik.http.middlewares.nextcloud-secure-headers.headers.hostsProxyHeaders=X-Forwarded-Host"
      - "traefik.http.middlewares.nextcloud-secure-headers.headers.referrerPolicy=same-origin"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-secure-headers"

volumes:
  nextcloud_aio_mastercontainer:
    external: true

networks:
  proxy:
    external: true