#https://github.com/nextcloud/all-in-one#nextcloud-all-in-one
#Built compose file from from https://github.com/nextcloud/all-in-one/blob/main/compose.yaml

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    #command: >
      #sh -c "update-ca-certificates && /start.sh"
    init: true
    restart: always
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - ${HOME}/services/caddy/certs/caddy-root.crt:/usr/local/share/ca-certificates/caddy-root.crt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    ports:
      - 8080:8080
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
      - APACHE_ADDITIONAL_NETWORK=proxy
volumes:
  nextcloud_aio_mastercontainer:
    external: true
networks:
  proxy:
    external: true