version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - proxy
    ports:
      - "3000:3000"
    volumes:
      - $HOME/services/homepage/config:/app/config:ro 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $HOME/services/homepage/images:/app/public/images:ro
      - $HOME/services/homepage/icons:/app/public/icons:ro
      - /mnt/sda:/mnt/sda:ro
    env_file: stack.env
    restart: unless-stopped

networks:
  proxy:
    external: true 