version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - proxy
    volumes:
      - $HOME/services/homepage/config:/app/config:ro 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $HOME/services/homepage/images:/app/public/images:ro
      - $HOME/services/homepage/icons:/app/public/icons:ro
      - /mnt/sda:/mnt/sda:ro
    env_file: stack.env
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`home.srv`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls=true"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
networks:
  proxy:
    external: true 