
#1. $UID and $GID can be fouund by using echo on host system
#2. An absolute path needs to be provided for the directory with your media in services.volumes.source

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: ${UID}:${GID}
    networks:
      - proxy
    volumes:
      - ${HOME}/services/jellyfin/config:/config
      - ${HOME}/services/jellyfin/cache:/cache
      - type: bind
        source: /home/username/Media #Bind mounts require absolute paths
        target: /media
        read_only: true
    restart: unless-stopped
    env_file: #Used for Portainer to add environment variables
      - stack.env
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    #extra_hosts:
      #- 'host.docker.internal:host-gateway'
    devices:
      - /dev/dri:/dev/dri  # Pass through the DRI device for hardware acceleration
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jelly.srv`)"
      - "traefik.http.routers.jellyfin.entrypoints=websecure"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
networks:
  proxy:
    external: true