services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerData:/data
    networks:
      - proxy
volumes:
  portainerData:
    external: true
networks:
  proxy:
    external: true